ws:
  wsPort: 2001
  barrageWsPort: 2002


rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: test-group   #生产者组名，规定在一个应用里面必须唯一
    send-message-timeout: 5000  #消息发送的超时时间，单位ms
    retry-times-when-send-async-failed: 5   #异步消息发送失败重试的次数
